services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taxcalculator
      MYSQL_USER: catalin
      MYSQL_PASSWORD: catalin
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - app-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tax-calculator
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/taxcalculator
      - SPRING_DATASOURCE_USERNAME=catalin
      - SPRING_DATASOURCE_PASSWORD=catalin
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    networks:
      - app-network



networks:
  app-network:
    driver: bridge