server:
  port: 8080
spring:
  application:
    name: "tax-calculator"
  profiles:
    active: "prod"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/taxcalculator
    username: catalin
    password: catalin
    driver-class-name: com.mysql.cj.jdbc.Driver
